from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import json
from typing import Any, Dict

from orchestration.task_model import Task
from .base import AgentResult


@dataclass
class ForgeAgent:
    """BUILDER (Forge) agent.

    Implements the role defined in V2_AGENT_ROLES:
    - generates project directory structure
    - generates backend and systems scaffolds
    - does not design architecture or run tests/deploys
    """

    name: str = "Builder"

    def _resolve_project_root(self, task: Task) -> Path:
        raw = task.inputs.get("project_root")
        base = Path(raw) if raw else Path("projects") / "session_default"
        base.mkdir(parents=True, exist_ok=True)
        return base

    def _load_architecture(self, project_root: Path) -> Dict[str, Any]:
        arch_path = project_root / "architecture.json"
        if arch_path.is_file():
            try:
                return json.loads(arch_path.read_text(encoding="utf-8"))
            except Exception:
                return {}
        return {}

    def handle_task(self, task: Task) -> AgentResult:
        project_root = self._resolve_project_root(task)
        _ = self._load_architecture(project_root)  # reserved for future richer mapping

        # Minimal but real project structure as per V2 roles.
        backend_root = project_root / "backend"
        gameplay_root = project_root / "gameplay"
        systems_root = project_root / "systems"
        scripts_root = project_root / "scripts"

        for root in (backend_root, gameplay_root, systems_root, scripts_root):
            root.mkdir(parents=True, exist_ok=True)

        # Create stub backend entrypoint and routing file.
        app_py = backend_root / "app.py"
        routes_py = backend_root / "routes.py"

        if not app_py.exists():
            app_py.write_text(
                """Minimal backend app scaffold generated by Forge.

from fastapi import FastAPI


app = FastAPI(title="Generated Project")


@app.get("/health")
async def health() -> dict:
    return {"status": "ok"}
""",
                encoding="utf-8",
            )

        if not routes_py.exists():
            routes_py.write_text(
                """Placeholder routes module for generated backend.

from fastapi import APIRouter


router = APIRouter()
""",
                encoding="utf-8",
            )

        created_paths = [
            str(app_py),
            str(routes_py),
            str(backend_root),
            str(gameplay_root),
            str(systems_root),
            str(scripts_root),
        ]

        return AgentResult(
            outputs={"created_paths": created_paths, "project_root": str(project_root)},
            logs=[f"Forge generated project scaffolding under {project_root}"],
        )
