"""Setup wizard API route.

Provides two endpoints used by the first-run wizard (``frontend/wizard.html``):

GET  /api/setup        — returns current configuration state (is setup complete?)
POST /api/setup/save   — persists submitted key/value pairs to ``config/.env``
POST /api/setup/reset  — clears ``SETUP_COMPLETE`` so the wizard shows again
"""

from __future__ import annotations

import asyncio
import logging
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List

from fastapi import APIRouter
from pydantic import BaseModel

logger = logging.getLogger(__name__)

router = APIRouter()

# The marker key written to config/.env once the wizard finishes.
_SETUP_COMPLETE_KEY = "SETUP_COMPLETE"

# All keys the wizard can write.  Any key not in this allow-list is silently
# ignored so that the route cannot be used to inject arbitrary env vars.
_ALLOWED_KEYS = {
    "AGENTFORGE_HOST",
    "AGENTFORGE_PORT",
    "PROVIDER_LLM",
    "OLLAMA_BASE_URL",
    "OLLAMA_MODEL",
    "OPENAI_API_KEY",
    "PROVIDER_IMAGE",
    "COMFYUI_BASE_URL",
    "FAL_API_KEY",
    "PROVIDER_TTS",
    "PIPER_MODEL_PATH",
    "BRIDGE_ROOT",
    "LOG_LEVEL",
    _SETUP_COMPLETE_KEY,
}


def _env_path() -> Path:
    return Path(__file__).resolve().parent.parent.parent / "config" / ".env"


def _read_env_file(path: Path) -> Dict[str, str]:
    """Parse the .env file into a dict (key → raw value)."""
    result: Dict[str, str] = {}
    if not path.exists():
        return result
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = (p.strip() for p in stripped.split("=", 1))
        if key:
            result[key] = value
    return result


def _write_env_file(path: Path, data: Dict[str, str]) -> None:
    """Atomically write a dict of key/value pairs to a .env file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# AgentForgeOS — auto-generated by setup wizard\n",
        "# Edit manually or re-run the wizard to change values.\n",
        "\n",
    ]
    for key, value in sorted(data.items()):
        # Quote values that contain spaces
        quoted = f'"{value}"' if " " in value else value
        lines.append(f"{key}={quoted}\n")
    path.write_text("".join(lines), encoding="utf-8")


class SaveConfigRequest(BaseModel):
    config: Dict[str, Any]


class BootstrapRequest(BaseModel):
    """Request payload for dependency bootstrap."""

    install_desktop: bool = False


@router.get("/setup", tags=["setup"])
async def get_setup_state():
    """Return the current configuration state.

    ``data.setup_complete`` is ``True`` when ``SETUP_COMPLETE=1`` is present
    in ``config/.env``.  The response also includes which keys are currently
    set (values are **not** returned to avoid leaking secrets over the API).
    """
    env = _read_env_file(_env_path())
    setup_complete = env.get(_SETUP_COMPLETE_KEY, "").strip() == "1"
    set_keys = [k for k, v in env.items() if v.strip()]
    return {
        "success": True,
        "data": {
            "setup_complete": setup_complete,
            "set_keys": set_keys,
            "env_file_exists": _env_path().exists(),
        },
        "error": None,
    }


@router.post("/setup/save", tags=["setup"])
async def save_config(body: SaveConfigRequest):
    """Persist the wizard's submitted values to ``config/.env``.

    Only keys in the allow-list are written.  Unknown keys are silently
    dropped.  After writing, ``SETUP_COMPLETE=1`` is added automatically so
    the main Studio page no longer redirects to the wizard.
    """
    path = _env_path()
    # Load existing values so we don't overwrite keys the user hasn't touched.
    existing = _read_env_file(path)
    for key, value in body.config.items():
        if key not in _ALLOWED_KEYS:
            logger.warning("Setup wizard: ignoring disallowed key '%s'", key)
            continue
        str_value = str(value).strip()
        if str_value:
            existing[key] = str_value
    # Mark setup as done
    existing[_SETUP_COMPLETE_KEY] = "1"
    _write_env_file(path, existing)
    # Reload into current process environment
    for key, value in existing.items():
        os.environ.setdefault(key, value)
    logger.info("Setup wizard: config saved to %s", path)
    return {"success": True, "data": {"saved": True}, "error": None}


@router.post("/setup/reset", tags=["setup"])
async def reset_setup():
    """Remove the ``SETUP_COMPLETE`` flag so the wizard is shown again."""
    path = _env_path()
    existing = _read_env_file(path)
    existing.pop(_SETUP_COMPLETE_KEY, None)
    os.environ.pop(_SETUP_COMPLETE_KEY, None)
    _write_env_file(path, existing)
    return {"success": True, "data": {"reset": True}, "error": None}


def _run_command(cmd: List[str], cwd: Path) -> Dict[str, Any]:
    """Run a command and capture stdout/stderr."""
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=300,
        )
        return {
            "cmd": " ".join(cmd),
            "returncode": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
        }
    except FileNotFoundError as exc:
        return {
            "cmd": " ".join(cmd),
            "returncode": -1,
            "stdout": "",
            "stderr": f"Executable not found: {exc}",
        }
    except subprocess.TimeoutExpired as exc:
        return {
            "cmd": " ".join(cmd),
            "returncode": -1,
            "stdout": exc.stdout or "",
            "stderr": f"Command timed out after {exc.timeout} seconds\n{exc.stderr or ''}",
        }


@router.post("/setup/bootstrap", tags=["setup"])
async def bootstrap(body: BootstrapRequest):
    """Run dependency installation for the host environment.

    This is a best-effort helper so the wizard can install required
    dependencies without leaving the UI. Commands are executed from the repo
    root and their output is returned to the caller.
    """

    repo_root = Path(__file__).resolve().parent.parent.parent

    # Always use the current Python interpreter for installs so that
    # bootstrap respects the active virtual environment on Windows and
    # other platforms. This avoids relying on "python"/"pip" being on PATH.
    python_exe = sys.executable or "python"

    commands: List[Dict[str, Any]] = [
        {"cmd": [python_exe, "-m", "pip", "install", "--upgrade", "pip"], "cwd": repo_root},
        {"cmd": [python_exe, "-m", "pip", "install", "-r", "requirements.txt"], "cwd": repo_root},
    ]
    if body.install_desktop:
        commands.append({"cmd": ["npm", "install"], "cwd": repo_root / "desktop"})

    results = []
    success = True
    for entry in commands:
        result = await asyncio.to_thread(_run_command, entry["cmd"], entry["cwd"])
        results.append(result)
        if result["returncode"] != 0:
            success = False
            break

    return {
        "success": success,
        "data": {"commands": results},
        "error": None if success else "One or more install commands failed",
    }
