"""Setup wizard API route.

Provides two endpoints used by the first-run wizard (``frontend/wizard.html``):

GET  /api/setup        — returns current configuration state (is setup complete?)
POST /api/setup/save   — persists submitted key/value pairs to ``config/.env``
POST /api/setup/reset  — clears ``SETUP_COMPLETE`` so the wizard shows again
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any, Dict

from fastapi import APIRouter
from pydantic import BaseModel

logger = logging.getLogger(__name__)

router = APIRouter()

# The marker key written to config/.env once the wizard finishes.
_SETUP_COMPLETE_KEY = "SETUP_COMPLETE"

# All keys the wizard can write.  Any key not in this allow-list is silently
# ignored so that the route cannot be used to inject arbitrary env vars.
_ALLOWED_KEYS = {
    "AGENTFORGE_HOST",
    "AGENTFORGE_PORT",
    "PROVIDER_LLM",
    "OLLAMA_BASE_URL",
    "OLLAMA_MODEL",
    "OPENAI_API_KEY",
    "PROVIDER_IMAGE",
    "COMFYUI_BASE_URL",
    "FAL_API_KEY",
    "PROVIDER_TTS",
    "PIPER_MODEL_PATH",
    "BRIDGE_ROOT",
    "LOG_LEVEL",
    _SETUP_COMPLETE_KEY,
}


def _env_path() -> Path:
    return Path(__file__).resolve().parent.parent.parent / "config" / ".env"


def _read_env_file(path: Path) -> Dict[str, str]:
    """Parse the .env file into a dict (key → raw value)."""
    result: Dict[str, str] = {}
    if not path.exists():
        return result
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = (p.strip() for p in stripped.split("=", 1))
        if key:
            result[key] = value
    return result


def _write_env_file(path: Path, data: Dict[str, str]) -> None:
    """Atomically write a dict of key/value pairs to a .env file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# AgentForgeOS — auto-generated by setup wizard\n",
        "# Edit manually or re-run the wizard to change values.\n",
        "\n",
    ]
    for key, value in sorted(data.items()):
        # Quote values that contain spaces
        quoted = f'"{value}"' if " " in value else value
        lines.append(f"{key}={quoted}\n")
    path.write_text("".join(lines), encoding="utf-8")


class SaveConfigRequest(BaseModel):
    config: Dict[str, Any]


@router.get("/setup", tags=["setup"])
async def get_setup_state():
    """Return the current configuration state.

    ``data.setup_complete`` is ``True`` when ``SETUP_COMPLETE=1`` is present
    in ``config/.env``.  The response also includes which keys are currently
    set (values are **not** returned to avoid leaking secrets over the API).
    """
    env = _read_env_file(_env_path())
    setup_complete = env.get(_SETUP_COMPLETE_KEY, "").strip() == "1"
    set_keys = [k for k, v in env.items() if v.strip()]
    return {
        "success": True,
        "data": {
            "setup_complete": setup_complete,
            "set_keys": set_keys,
            "env_file_exists": _env_path().exists(),
        },
        "error": None,
    }


@router.post("/setup/save", tags=["setup"])
async def save_config(body: SaveConfigRequest):
    """Persist the wizard's submitted values to ``config/.env``.

    Only keys in the allow-list are written.  Unknown keys are silently
    dropped.  After writing, ``SETUP_COMPLETE=1`` is added automatically so
    the main Studio page no longer redirects to the wizard.
    """
    path = _env_path()
    # Load existing values so we don't overwrite keys the user hasn't touched.
    existing = _read_env_file(path)
    for key, value in body.config.items():
        if key not in _ALLOWED_KEYS:
            logger.warning("Setup wizard: ignoring disallowed key '%s'", key)
            continue
        str_value = str(value).strip()
        if str_value:
            existing[key] = str_value
    # Mark setup as done
    existing[_SETUP_COMPLETE_KEY] = "1"
    _write_env_file(path, existing)
    # Reload into current process environment
    for key, value in existing.items():
        os.environ.setdefault(key, value)
    logger.info("Setup wizard: config saved to %s", path)
    return {"success": True, "data": {"saved": True}, "error": None}


@router.post("/setup/reset", tags=["setup"])
async def reset_setup():
    """Remove the ``SETUP_COMPLETE`` flag so the wizard is shown again."""
    path = _env_path()
    existing = _read_env_file(path)
    existing.pop(_SETUP_COMPLETE_KEY, None)
    os.environ.pop(_SETUP_COMPLETE_KEY, None)
    _write_env_file(path, existing)
    return {"success": True, "data": {"reset": True}, "error": None}
