"""Setup wizard API route.

Provides endpoints used by the first-run wizard (``frontend/wizard.html``):

GET  /api/setup        — returns current setup state (is setup complete?)
POST /api/setup/save   — persists settings
POST /api/setup/reset  — clears setup completion so the wizard shows again

Persistence targets:
- Developer env: ``config/.env`` (for local runs)
- Desktop install: ``resources/config.json`` and ``resources/providers.json`` (Build Bible)
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List

from fastapi import APIRouter, Request, Response
from pydantic import BaseModel

logger = logging.getLogger(__name__)

router = APIRouter()

# The marker key written to config/.env once the wizard finishes.
_SETUP_COMPLETE_KEY = "SETUP_COMPLETE"

# All keys the wizard can write.  Any key not in this allow-list is silently
# ignored so that the route cannot be used to inject arbitrary env vars.
_ALLOWED_KEYS = {
    "AGENTFORGE_HOST",
    "AGENTFORGE_PORT",
    "WORKSPACE_PATH",
    "AGENTFORGE_MONGO_URI",
    "AGENTFORGE_MONGO_DB",
    "AGENTFORGE_UNITY_EXE",
    "AGENTFORGE_UNREAL_EXE",
    "PROVIDER_LLM",
    "OLLAMA_BASE_URL",
    "OLLAMA_MODEL",
    "OPENAI_API_KEY",
    "OPENAI_MODEL",
    "PROVIDER_IMAGE",
    "COMFYUI_BASE_URL",
    "FAL_API_KEY",
    "FAL_LLM_MODEL",
    "PROVIDER_TTS",
    "PIPER_MODEL_PATH",
    "BRIDGE_ROOT",
    "LOG_LEVEL",
    _SETUP_COMPLETE_KEY,
}


def _env_path() -> Path:
    return Path(__file__).resolve().parent.parent.parent / "config" / ".env"


def _read_env_file(path: Path) -> Dict[str, str]:
    """Parse the .env file into a dict (key → raw value)."""
    result: Dict[str, str] = {}
    if not path.exists():
        return result
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = (p.strip() for p in stripped.split("=", 1))
        if key:
            result[key] = value
    return result


def _write_env_file(path: Path, data: Dict[str, str]) -> None:
    """Atomically write a dict of key/value pairs to a .env file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# AgentForgeOS — auto-generated by setup wizard\n",
        "# Edit manually or re-run the wizard to change values.\n",
        "\n",
    ]
    for key, value in sorted(data.items()):
        # Quote values that contain spaces
        quoted = f'"{value}"' if " " in value else value
        lines.append(f"{key}={quoted}\n")
    path.write_text("".join(lines), encoding="utf-8")


class SaveConfigRequest(BaseModel):
    config: Dict[str, Any]


class SetupTestRequest(BaseModel):
    config: Dict[str, Any]


class BootstrapRequest(BaseModel):
    """Request payload for dependency bootstrap."""

    install_desktop: bool = False


@router.get("/setup", tags=["setup"])
async def get_setup_state():
    """Return the current configuration state.

    ``data.setup_complete`` is ``True`` when ``SETUP_COMPLETE=1`` is present
    in ``config/.env``.  The response also includes which keys are currently
    set (values are **not** returned to avoid leaking secrets over the API).
    """
    env = _read_env_file(_env_path())
    setup_complete = env.get(_SETUP_COMPLETE_KEY, "").strip() == "1"
    set_keys = [k for k, v in env.items() if v.strip()]
    return {
        "success": True,
        "data": {
            "setup_complete": setup_complete,
            "set_keys": set_keys,
            "env_file_exists": _env_path().exists(),
        },
        "error": None,
    }


@router.post("/setup/save", tags=["setup"])
async def save_config(body: SaveConfigRequest, request: Request, response: Response):
    """Persist the wizard's submitted values to ``config/.env``.

    Only keys in the allow-list are written.  Unknown keys are silently
    dropped.  After writing, ``SETUP_COMPLETE=1`` is added automatically so
    the main Studio page no longer redirects to the wizard.
    """
    path = _env_path()
    # Load existing values so we don't overwrite keys the user hasn't touched.
    existing = _read_env_file(path)
    applied: Dict[str, str] = {}
    for key, value in body.config.items():
        if key not in _ALLOWED_KEYS:
            logger.warning("Setup wizard: ignoring disallowed key '%s'", key)
            continue
        str_value = str(value).strip()
        if str_value:
            existing[key] = str_value
            applied[key] = str_value
    # Mark setup as done
    existing[_SETUP_COMPLETE_KEY] = "1"
    _write_env_file(path, existing)
    # Reload into current process environment
    os.environ[_SETUP_COMPLETE_KEY] = "1"
    for key, value in applied.items():
        os.environ[key] = value
    logger.info("Setup wizard: config saved to %s", path)
    _write_desktop_resources(body.config)
    try:
        exe_base = Path(getattr(request.app.state, "base_path", "") or _get_exe_base_path())
        cfg_path = _resources_root(exe_base) / "config.json"
        if cfg_path.is_file():
            loaded = _read_json(cfg_path)
            request.app.state.config = dict(loaded) if isinstance(loaded, dict) else {}
        ws_override = str(existing.get("WORKSPACE_PATH") or "").strip()
        if ws_override:
            request.app.state.workspace_path = ws_override
        else:
            ws_cfg = ""
            cfg_raw = getattr(request.app.state, "config", {}) or {}
            if isinstance(cfg_raw, dict):
                ws_cfg = str(cfg_raw.get("workspace_path") or "").strip()
            if ws_cfg:
                request.app.state.workspace_path = ws_cfg
    except Exception:
        pass

    try:
        provider_llm = str(existing.get("PROVIDER_LLM") or "").strip().lower()
        fal_api_key = str(existing.get("FAL_API_KEY") or "").strip()
        fal_model = str(existing.get("FAL_LLM_MODEL") or "").strip()
        if provider_llm == "fal" and fal_api_key:
            from engine.router import config_loader as engine_cfg_loader

            exe_base = Path(getattr(request.app.state, "base_path", "") or _get_exe_base_path())
            override = engine_cfg_loader.load_engine_config_user_override(exe_base=exe_base)
            next_override: Dict[str, Any] = dict(override) if isinstance(override, dict) else {}
            api_keys = next_override.get("api_keys")
            api_keys = dict(api_keys) if isinstance(api_keys, dict) else {}
            api_keys["fal"] = fal_api_key
            next_override["api_keys"] = api_keys
            enabled = next_override.get("enabled_engines")
            enabled_list = [e for e in enabled if isinstance(e, str)] if isinstance(enabled, list) else []
            if "fal" not in enabled_list:
                enabled_list.append("fal")
            next_override["enabled_engines"] = enabled_list
            if fal_model:
                engines = next_override.get("engines")
                engines = dict(engines) if isinstance(engines, dict) else {}
                fal_engine = engines.get("fal")
                fal_engine = dict(fal_engine) if isinstance(fal_engine, dict) else {}
                fal_engine.setdefault("model", fal_model)
                engines["fal"] = fal_engine
                next_override["engines"] = engines
            engine_cfg_loader.save_engine_config_user_override(next_override, exe_base=exe_base)
    except Exception:
        pass
    token = os.environ.get("AGENTFORGE_BRIDGE_TOKEN", "").strip()
    if not token:
        exe_base = _get_exe_base_path()
        cfg_path = _resources_root(exe_base) / "config.json"
        try:
            if cfg_path.is_file():
                cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
                token = str(cfg.get("bridge_token") or "").strip()
        except Exception:
            token = ""
    if token:
        response.set_cookie(
            key="agentforge_session",
            value=token,
            httponly=True,
            samesite="lax",
        )
    return {"success": True, "data": {"saved": True}, "error": None}


def _ok(ok: bool, detail: str) -> dict[str, Any]:
    return {"ok": bool(ok), "detail": detail}


async def _http_ok(url: str) -> tuple[bool, str]:
    try:
        import httpx  # type: ignore
    except Exception:
        return False, "httpx unavailable"
    try:
        async with httpx.AsyncClient(timeout=2.5) as client:
            resp = await client.get(url)
            if 200 <= resp.status_code < 300:
                return True, f"{resp.status_code}"
            return False, f"{resp.status_code}"
    except Exception as exc:
        return False, str(exc)


async def _mongo_ok(uri: str) -> tuple[bool, str]:
    try:
        from motor.motor_asyncio import AsyncIOMotorClient  # type: ignore
    except Exception:
        return False, "motor unavailable"
    try:
        client = AsyncIOMotorClient(uri, serverSelectionTimeoutMS=1500)
        await client.admin.command("ping")
        client.close()
        return True, "ping ok"
    except Exception as exc:
        try:
            client.close()
        except Exception:
            pass
        return False, str(exc)


@router.post("/setup/test", tags=["setup"])
async def test_setup(body: SetupTestRequest, type: str | None = None) -> dict[str, Any]:
    incoming = body.config if isinstance(body.config, dict) else {}
    cfg: Dict[str, str] = {}
    for k, v in incoming.items():
        if k not in _ALLOWED_KEYS:
            continue
        s = str(v).strip()
        if s:
            cfg[k] = s

    results: dict[str, Any] = {}
    want = (type or "").strip().lower()
    want = want or None

    if want in {None, "engine"}:
        results["engine"] = _ok(True, "ok")

    if want in {None, "llm"}:
        llm = str(cfg.get("PROVIDER_LLM") or "").strip().lower()
        if llm == "ollama":
            base_url = str(cfg.get("OLLAMA_BASE_URL") or "http://localhost:11434").strip()
            ok, detail = await _http_ok(f"{base_url.rstrip('/')}/api/tags")
            results["llm"] = _ok(ok, f"ollama: {detail}")
        elif llm == "openai":
            api_key = str(cfg.get("OPENAI_API_KEY") or "").strip()
            results["llm"] = _ok(bool(api_key), "openai: api_key configured" if api_key else "openai: missing api_key")
        elif llm == "fal":
            api_key = str(cfg.get("FAL_API_KEY") or "").strip()
            model = str(cfg.get("FAL_LLM_MODEL") or "").strip()
            if not api_key:
                results["llm"] = _ok(False, "fal: missing api_key")
            else:
                try:
                    from providers.fal_llm_provider import FalLLMProvider

                    provider = FalLLMProvider(api_key=api_key, model=model or None, timeout=12.0)
                    resp = await provider.chat("ping")
                    ok = bool(resp.get("success"))
                    err = str(resp.get("error") or "").strip()
                    results["llm"] = _ok(ok, "fal: ok" if ok else f"fal: {err or 'failed'}")
                except Exception as exc:
                    results["llm"] = _ok(False, f"fal: {exc}")
        elif llm:
            results["llm"] = _ok(False, f"unknown llm provider: {llm}")
        else:
            results["llm"] = _ok(False, "no llm provider selected")

    if want in {None, "image"}:
        image = str(cfg.get("PROVIDER_IMAGE") or "").strip().lower()
        if image == "comfyui":
            base_url = str(cfg.get("COMFYUI_BASE_URL") or "http://localhost:8188").strip()
            ok, detail = await _http_ok(f"{base_url.rstrip('/')}/system_stats")
            results["image"] = _ok(ok, f"comfyui: {detail}")
        elif image == "fal":
            api_key = str(cfg.get("FAL_API_KEY") or "").strip()
            results["image"] = _ok(bool(api_key), "fal: api_key configured" if api_key else "fal: missing api_key")
        elif image:
            results["image"] = _ok(False, f"unknown image provider: {image}")
        else:
            results["image"] = _ok(False, "no image provider selected")

    if want in {None, "tts"}:
        tts = str(cfg.get("PROVIDER_TTS") or "").strip().lower()
        if tts == "piper":
            model_path = str(cfg.get("PIPER_MODEL_PATH") or "").strip()
            ok = bool(model_path and Path(model_path).exists())
            results["tts"] = _ok(ok, "piper: model_path exists" if ok else "piper: model_path missing")
        elif tts:
            results["tts"] = _ok(False, f"unknown tts provider: {tts}")
        else:
            results["tts"] = _ok(True, "tts disabled")

    if want in {None, "mongo"}:
        uri = str(cfg.get("AGENTFORGE_MONGO_URI") or "").strip()
        if not uri:
            results["mongo"] = _ok(True, "mongo disabled")
        else:
            ok, detail = await _mongo_ok(uri)
            results["mongo"] = _ok(ok, f"mongo: {detail}")

    return {"success": True, "data": {"results": results}, "error": None}


@router.post("/setup/reset", tags=["setup"])
async def reset_setup():
    """Remove the ``SETUP_COMPLETE`` flag so the wizard is shown again."""
    path = _env_path()
    existing = _read_env_file(path)
    existing.pop(_SETUP_COMPLETE_KEY, None)
    os.environ.pop(_SETUP_COMPLETE_KEY, None)
    _write_env_file(path, existing)
    return {"success": True, "data": {"reset": True}, "error": None}


def _run_command(cmd: List[str], cwd: Path) -> Dict[str, Any]:
    """Run a command and capture stdout/stderr."""
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=300,
        )
        return {
            "cmd": " ".join(cmd),
            "returncode": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
        }
    except FileNotFoundError as exc:
        return {
            "cmd": " ".join(cmd),
            "returncode": -1,
            "stdout": "",
            "stderr": f"Executable not found: {exc}",
        }
    except subprocess.TimeoutExpired as exc:
        return {
            "cmd": " ".join(cmd),
            "returncode": -1,
            "stdout": exc.stdout or "",
            "stderr": f"Command timed out after {exc.timeout} seconds\n{exc.stderr or ''}",
        }


def _get_exe_base_path() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parent.parent.parent


def _resources_root(exe_base: Path) -> Path:
    if exe_base.name.lower() == "resources":
        return exe_base
    return exe_base / "resources"


def _safe_int(value: Any, default: int) -> int:
    try:
        return int(value)
    except Exception:
        return default


def _read_json(path: Path) -> Dict[str, Any]:
    try:
        if path.is_file():
            return dict(__import__("json").loads(path.read_text(encoding="utf-8")))
    except Exception:
        return {}
    return {}


def _write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(__import__("json").dumps(data, indent=2), encoding="utf-8")


def _write_desktop_resources(config: Dict[str, Any]) -> None:
    exe_base = _get_exe_base_path()
    resources_dir = _resources_root(exe_base)
    resources_dir.mkdir(parents=True, exist_ok=True)
    config_path = resources_dir / "config.json"
    providers_path = resources_dir / "providers.json"

    existing_config = _read_json(config_path)
    existing_providers = _read_json(providers_path)

    server = dict(existing_config.get("server") or {})
    server["host"] = str(config.get("AGENTFORGE_HOST", server.get("host", "127.0.0.1"))).strip() or "127.0.0.1"
    server["port"] = _safe_int(config.get("AGENTFORGE_PORT", server.get("port", 8000)), 8000)
    existing_config["server"] = server

    if "WORKSPACE_PATH" in config and str(config.get("WORKSPACE_PATH") or "").strip():
        existing_config["workspace_path"] = str(config["WORKSPACE_PATH"]).strip()

    mongo = dict(existing_config.get("mongo") or {})
    if "AGENTFORGE_MONGO_URI" in config and str(config.get("AGENTFORGE_MONGO_URI") or "").strip():
        mongo["uri"] = str(config["AGENTFORGE_MONGO_URI"]).strip()
    if "AGENTFORGE_MONGO_DB" in config and str(config.get("AGENTFORGE_MONGO_DB") or "").strip():
        mongo["db"] = str(config["AGENTFORGE_MONGO_DB"]).strip()
    if mongo:
        existing_config["mongo"] = mongo

    bridge = dict(existing_config.get("bridge") or {})
    if "BRIDGE_ROOT" in config and str(config.get("BRIDGE_ROOT") or "").strip():
        bridge["root"] = str(config["BRIDGE_ROOT"]).strip()
    existing_config["bridge"] = bridge

    logging_cfg = dict(existing_config.get("logging") or {})
    if "LOG_LEVEL" in config and str(config.get("LOG_LEVEL") or "").strip():
        logging_cfg["level"] = str(config["LOG_LEVEL"]).strip()
    existing_config["logging"] = logging_cfg

    providers = dict(existing_config.get("providers") or {})
    if "PROVIDER_LLM" in config and str(config.get("PROVIDER_LLM") or "").strip():
        providers["llm"] = str(config["PROVIDER_LLM"]).strip()
    if "PROVIDER_IMAGE" in config:
        providers["image"] = str(config.get("PROVIDER_IMAGE") or "").strip()
    if "PROVIDER_TTS" in config:
        providers["tts"] = str(config.get("PROVIDER_TTS") or "").strip()
    existing_config["providers"] = providers

    ollama = dict(existing_config.get("ollama") or {})
    if "OLLAMA_BASE_URL" in config and str(config.get("OLLAMA_BASE_URL") or "").strip():
        ollama["base_url"] = str(config["OLLAMA_BASE_URL"]).strip()
    if "OLLAMA_MODEL" in config and str(config.get("OLLAMA_MODEL") or "").strip():
        ollama["model"] = str(config["OLLAMA_MODEL"]).strip()
    existing_config["ollama"] = ollama

    comfyui = dict(existing_config.get("comfyui") or {})
    if "COMFYUI_BASE_URL" in config and str(config.get("COMFYUI_BASE_URL") or "").strip():
        comfyui["base_url"] = str(config["COMFYUI_BASE_URL"]).strip()
    existing_config["comfyui"] = comfyui

    piper = dict(existing_config.get("piper") or {})
    if "PIPER_MODEL_PATH" in config and str(config.get("PIPER_MODEL_PATH") or "").strip():
        piper["model_path"] = str(config["PIPER_MODEL_PATH"]).strip()
    existing_config["piper"] = piper

    openai_cfg = dict(existing_providers.get("openai") or {})
    if "OPENAI_API_KEY" in config and str(config.get("OPENAI_API_KEY") or "").strip():
        openai_cfg["api_key"] = str(config["OPENAI_API_KEY"]).strip()
    if "OPENAI_MODEL" in config and str(config.get("OPENAI_MODEL") or "").strip():
        openai_cfg["model"] = str(config["OPENAI_MODEL"]).strip()
    if openai_cfg:
        existing_providers["openai"] = openai_cfg

    fal_cfg = dict(existing_providers.get("fal") or {})
    if "FAL_API_KEY" in config and str(config.get("FAL_API_KEY") or "").strip():
        fal_cfg["api_key"] = str(config["FAL_API_KEY"]).strip()
    if "FAL_LLM_MODEL" in config and str(config.get("FAL_LLM_MODEL") or "").strip():
        fal_cfg["model"] = str(config["FAL_LLM_MODEL"]).strip()
    if fal_cfg:
        existing_providers["fal"] = fal_cfg

    _write_json(config_path, existing_config)
    _write_json(providers_path, existing_providers)


@router.post("/setup/bootstrap", tags=["setup"])
async def bootstrap(body: BootstrapRequest):
    """Run dependency installation for the host environment.

    This is a best-effort helper so the wizard can install required
    dependencies without leaving the UI. Commands are executed from the repo
    root and their output is returned to the caller.
    """

    repo_root = Path(__file__).resolve().parent.parent.parent

    # Always use the current Python interpreter for installs so that
    # bootstrap respects the active virtual environment on Windows and
    # other platforms. This avoids relying on "python"/"pip" being on PATH.
    python_exe = sys.executable or "python"

    commands: List[Dict[str, Any]] = [
        {"cmd": [python_exe, "-m", "pip", "install", "--upgrade", "pip"], "cwd": repo_root},
        {"cmd": [python_exe, "-m", "pip", "install", "-r", "requirements.txt"], "cwd": repo_root},
    ]
    if body.install_desktop:
        commands.append({"cmd": ["npm", "install"], "cwd": repo_root / "desktop"})

    results = []
    success = True
    for entry in commands:
        result = await asyncio.to_thread(_run_command, entry["cmd"], entry["cwd"])
        results.append(result)
        if result["returncode"] != 0:
            success = False
            break

    return {
        "success": success,
        "data": {"commands": results},
        "error": None if success else "One or more install commands failed",
    }
